dataset:
  name: PDE_KS
  pair_id: 'all'
model:
  name: DeepONet
  lag: 50
  branch_layers: 3
  trunk_layers: 3
  neurons: 128
  activation: "tanh"
  initialization: "Glorot normal"
  optimizer: "adam"
  learning_rate: 0.001
  epochs: 10000
