dataset:
  name: ODE_Lorenz
  pair_id: 'all'
model:
  name: DeepONet
  lag: 1
  branch_layers: 4
  trunk_layers: 4
  neurons: 128
  activation: "tanh"
  initialization: "Glorot normal"
  optimizer: "adam"
  learning_rate: 0.001
  epochs: 10000
  batch_size: 32