dataset:
  name: ODE_Lorenz
  pair_id:
  - 8
model:
  activation: tanh
  branch_layers: 1
  epochs: 10000
  initialization: He normal
  lag: 21
  learning_rate: 0.03231476023959178
  method: constant
  name: DeepONet
  neurons: 2
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 2
