dataset:
  name: PDE_KS
  pair_id: [5]
model:
  activation: tanh
  branch_layers: 4
  epochs: 10000
  initialization: Glorot normal
  lag: 33
  learning_rate: 0.005254365369209532
  method: constant
  name: DeepONet
  neurons: 105
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 1
