dataset:
  name: PDE_KS
  pair_id: [6]
model:
  activation: tanh
  branch_layers: 3
  epochs: 10000
  initialization: Glorot normal
  lag: 15
  learning_rate: 0.011662254514496357
  method: constant
  name: DeepONet
  neurons: 68
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 3