dataset:
  name: ODE_Lorenz
  pair_id: [9]
model:
  activation: tanh
  batch_size: 32
  branch_layers: 3
  epochs: 10000
  initialization: Glorot normal
  lag: 90
  learning_rate: 0.001
  name: DeepONet
  neurons: 256
  optimizer: adam
  trunk_layers: 3