dataset:
  name: PDE_KS
  pair_id:
  - 3
model:
  activation: elu
  branch_layers: 4
  epochs: 10000
  initialization: Glorot normal
  lag: 14
  learning_rate: 0.0038806532185837826
  method: constant
  name: DeepONet
  neurons: 197
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 4
