dataset:
  name: PDE_KS
  pair_id: [2]
model:
  activation: tanh
  branch_layers: 3
  epochs: 10000
  initialization: Glorot normal
  lag: 50
  learning_rate: 0.001
  name: DeepONet
  neurons: 128
  optimizer: adam
  trunk_layers: 3