dataset:
  name: PDE_KS
  pair_id: [7]
model:
  activation: relu
  branch_layers: 1
  epochs: 10000
  initialization: Glorot normal
  lag: 14
  learning_rate: 0.019515351164244785
  method: constant
  name: DeepONet
  neurons: 9
  optimizer: adam
  seed: 0
  trunk_layers: 3
