dataset:
  name: PDE_KS
  pair_id:
  - 2
model:
  activation: tanh
  branch_layers: 2
  epochs: 10000
  initialization: He normal
  lag: 49
  learning_rate: 0.0001658906851793589
  method: constant
  name: DeepONet
  neurons: 421
  optimizer: adam
  seed: 0
  trunk_layers: 1
