dataset:
  name: ODE_Lorenz
  pair_id:
  - 7
model:
  activation: tanh
  branch_layers: 2
  epochs: 10000
  initialization: Glorot normal
  lag: 37
  learning_rate: 0.007291315594622275
  method: constant
  name: DeepONet
  neurons: 56
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 1
