dataset:
  name: ODE_Lorenz
  pair_id: [1,2,3,4,5,6,7,8,9]
model:
  name: DeepONet
  train_split: 0.8
  seed: 0
  n_trials: 3
  method: 'constant'
hyperparameters: # Specify hyperparameters and ranges
  lag:
    type: randint
    lower_bound: 1
    upper_bound: 50
  branch_layers:
    type: randint
    lower_bound: 1
    upper_bound: 10
  trunk_layers:
    type: randint
    lower_bound: 1
    upper_bound: 10
  branch_neurons:
    type: randint
    lower_bound: 1
    upper_bound: 1024
  trunk_neurons:
    type: randint
    lower_bound: 1
    upper_bound: 1024
  activation:
    type: choice
    values: ["tanh", "relu", "elu"]
  initialization:
    type: choice
    values: ["Glorot normal", "He normal"]
  optimizer:
    type: choice
    values: ["adam", "L-BFGS"]
  learning_rate:
    type: loguniform
    lower_bound: 1e-5
    upper_bound: 1e-1
  epochs:
    type: randint
    lower_bound: 100
    upper_bound: 50000
  batch_size:
    type: randint
    lower_bound: 1
    upper_bound: 32