dataset:
  name: ODE_Lorenz
  pair_id: [1]
model:
  name: DeepONet
  train_split: 0.8
  seed: 0
  n_trials: 100
  method: 'constant'
  epochs: 10000
hyperparameters: # Specify hyperparameters and ranges
  lag:
    type: randint
    lower_bound: 1
    upper_bound: 99
  branch_layers:
    type: randint
    lower_bound: 1
    upper_bound: 5
  trunk_layers:
    type: randint
    lower_bound: 1
    upper_bound: 5
  neurons:
    type: randint
    lower_bound: 1
    upper_bound: 512
  activation:
    type: choice
    choices: ["tanh", "relu", "elu"]
  initialization:
    type: choice
    choices: ["Glorot normal", "He normal"]
  optimizer:
    type: choice
    choices: ["adam", "L-BFGS"]
  learning_rate:
    type: loguniform
    lower_bound: 1.e-4
    upper_bound: 1.e-1